"""
C:/Users/Gi/Desktop/PSM_Data/16_generate_new_models_lua.py

Purpose
-------
Generate a new ModelsData.lua file that:
  • Places the *numeric* NPC ID at position 1.
  • Keeps zone_name (not uiMapName) as the second column for backward compatibility.
  • Adds uiMapId and uiMapName as new columns.
  • Emits a clear Lua header describing the column order.

This script reads from pet_data.csv and outputs ModelsData.lua with the
numeric NPC ID in position 1 and a lookup table for display names.
"""

import csv
import os
import sys
import re
from collections import OrderedDict

# ----------------------------------------------------------------------
# 1️⃣ Configuration & Constants
# ----------------------------------------------------------------------
# Using raw strings for Windows paths
PROCESSED_PET_DATA_CSV  = r"c:\Users\Gi\Desktop\PSM_Data\Processed\pet_data.csv"
OUTPUT_MODELS_LUA       = r"c:\Users\Gi\Desktop\PSM_Dev\PetStableManagement\Output\ModelsData.lua"

# Expansion mapping (patch ID → friendly name)
EXPANSION_MAPPING = {
    1: "Vanilla", 2: "The Burning Crusade", 3: "Wrath of the Lich King",
    4: "Cataclysm", 5: "Mists of Pandaria", 6: "Warlords of Draenor",
    7: "Legion", 8: "Battle for Azeroth", 9: "Shadowlands",
    10: "Dragonflight", 11: "The War Within", 12: "Midnight", 13: "The Last Titan"
}

TYPE_MAP = {
    '1': 'Beast', '2': 'Dragonkin', '4': 'Elemental',
    '6': 'Undead', '9': 'Mechanical', '15': 'Aberration'
}

# ----------------------------------------------------------------------
# 2️⃣ Helper Functions
# ----------------------------------------------------------------------
def _clean(val: str) -> str:
    """Strip whitespace / BOM and collapse newlines."""
    if not val:
        return ""
    val = val.replace("﻿", "").strip()
    return " ".join(val.splitlines())

def get_expansion(patch_id: str) -> str:
    """Convert patch_id to friendly expansion name."""
    if not patch_id:
        return ""
    try:
        pid = int(str(patch_id).split('.')[0])
        return EXPANSION_MAPPING.get(pid, "")
    except (ValueError, IndexError):
        return ""

def write_lua_array(records, output_path):
    """Write the ModelsData.lua file with proper Lua array format."""
    lines = [
        "-- Auto-generated by 16_generate_new_models_lua.py",
        "-- Column order in each NPC record:",
        "--   1: npc_id (numeric internal identifier)",
        "--   2: npc_name (display name)",
        "--   3: zone_name (legacy location string for compatibility)",
        "--   4: expansion",
        "--   5: classification (difficulty/reaction)",
        "--   6: uiMapId (numeric zone identifier)",
        "--   7: uiMapName (fallback zone name)",
        "--",
        "PSM = PSM or {}",
        "PSM.ModelsData = PSM.ModelsData or {}",
        "ModelsData = {}"
    ]

    unique_npcs = {}
    for row in records:
        npc_id = row['npc_id']
        if npc_id and npc_id.isdigit():
            if npc_id not in unique_npcs:
                unique_npcs[npc_id] = row

    for npc_id in sorted(unique_npcs.keys()):
        r = unique_npcs[npc_id]
        parts = [f'[{npc_id}] = {{']
        parts.append(f'    "{r["npc_name"]}",')
        parts.append(f'    "{r["zone_name"]}",')
        parts.append(f'    "{r["expansion"]}",')
        parts.append(f'    "{r["react"]}",')
        parts.append(f'    {r["uiMapId"] or "0"},')
        parts.append(f'    "{r["uiMapName"]}"')
        parts.append('},')
        lines.extend(parts)

    lines.append("return ModelsData")

    out_dir = os.path.dirname(output_path)
    os.makedirs(out_dir, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

# ----------------------------------------------------------------------
# 3️⃣ Main Generation Logic
# ----------------------------------------------------------------------
def generate_models_data():
    if not os.path.exists(PROCESSED_PET_DATA_CSV):
        print(f"Error: {PROCESSED_PET_DATA_CSV} not found. Run step 10 first.")
        sys.exit(1)

    records = []
    with open(PROCESSED_PET_DATA_CSV, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            npc_id = _clean(row.get("npc_id", ""))
            if not npc_id:
                continue

            records.append({
                "npc_id": npc_id,
                "npc_name": _clean(row.get("displayName", row.get("npc_name", ""))),
                "zone_name": _clean(row.get("zone_name", "")),
                "uiMapId": _clean(row.get("uiMapId", "0")),
                "uiMapName": _clean(row.get("uiMapName", "")),
                "expansion": get_expansion(_clean(row.get("patch_id", ""))),
                "react": _clean(row.get("react", ""))
            })

    write_lua_array(records, OUTPUT_MODELS_LUA)
    print(f"Generated {OUTPUT_MODELS_LUA} with {len(records)} NPC records.")

if __name__ == "__main__":
    generate_models_data()